import '../../styles/globals.css'

import { ReactNode } from 'react'

export const metadata = {
  title: 'Home | Thebrabus Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html>
      <body>{children}</body>
    </html>
  )
}
